version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "heagotest"
      POSTGRES_USER: "testgouser"
      POSTGRES_PASSWORD: "pgpwd4gotest"
    volumes:
      - pgdatago:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass mYPaSs_sEcUrE_pAsS
    ports:
        - "16379:6379"
    volumes:
        - redisdatago:/var/lib/redis
    environment:
        - REDIS_REPLICATION_MODE=master
volumes:
    pgdatago:
        external: true
    redisdatago:
        external: true
